# Generated by Django 4.2.30 on 2026-05-05 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('bench', 'Ghế đá'), ('trash_can', 'Thùng rác'), ('lamp', 'Cột đèn'), ('toilet', 'Nhà vệ sinh'), ('tree', 'Cây xanh'), ('sign', 'Biển báo')], max_length=50)),
                ('_latitude', models.FloatField(db_column='latitude', default=0)),
                ('_longitude', models.FloatField(db_column='longitude', default=0)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('damaged', 'Hư hỏng'), ('maintenance', 'Đang bảo trì')], default='active', max_length=20)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('last_maintained_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset_type', 'status'], name='assets_asset_t_3810fd_idx'), models.Index(fields=['-created_at'], name='assets_created_d09603_idx')],
            },
        ),
    ]
