# Generated by Django 4.2.30 on 2026-05-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('bbox_min_lng', models.FloatField()),
                ('bbox_min_lat', models.FloatField()),
                ('bbox_max_lng', models.FloatField()),
                ('bbox_max_lat', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['name'],
            },
        ),
    ]
