# Generated by Django 4.2.30 on 2026-05-05 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_latitude', models.FloatField(db_column='latitude', default=0)),
                ('_longitude', models.FloatField(db_column='longitude', default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('incident_type', models.CharField(choices=[('littering', 'Xả rác'), ('pothole', 'Ổ gà'), ('broken_lamp', 'Đèn hỏng'), ('vandalism', 'Phá hoại'), ('flooding', 'Ngập nước'), ('crowd', 'Tụ tập đông'), ('other', 'Khác')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Nghiêm trọng')], default='medium', max_length=20)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
